### ISSUE TITLE
UI/UX: Light & Dark Themes

### ISSUE THREAD

**Issue by altninja** [SelfKeyFoundation/selfkey-login#22]
Aha! Link: https://kycc.aha.io/features/SL-17

**Comment by oanamangiurea** [comment]
Dark mode is ready https://projects.invisionapp.com/d/main#/projects/prototypes/15164754

**Comment by oanamangiurea** [comment]
Light mode ready https://projects.invisionapp.com/d/main#/console/15164754/316016711/preview and next pages

Dark Mode CSS done https://drive.google.com/drive/u/0/folders/1ZVX_Us1DMHlmHdmTPa6QLDoO_GSkopsd
