### ISSUE TITLE
Bug: Unlocked Wallet Mismatch In Browser/Desktop

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/selfkey-login#27]
**Overview:**
You can login to a Trezor/Ledger address on the desktop application, and login to a different ETH address (Keystore File) in the LWS extension and still unlock it. Both addresses are different but also unlocked - perhaps extension doesn't check both ETH address values are the same before proceeding?

Reproduced with both TREZOR/Ledger and Keystore file. Understand hardware wallets still not fully integrated on the Login With SelfKey Side so this may be a dependency that will be fixed first.

**Steps To Reproduce:**
1) Login to SelfKey Identity Wallet with TREZOR or Ledger.
2) Create a SelfKey ID.
3) Go to localhost:8080 where test enviornment of local LWS build is
4) Login to a separate Keystore file different from TREZOR/Ledger on desktop application.
5) Note: KEY value of Keystore wallet will override the dashboard amount in desktop application. Basically, values of KEY on Ledger/Trezor address get overwritten.

**Screenshot:**
![mysterious key values merged](https://user-images.githubusercontent.com/30673971/44371375-9c651300-a4ac-11e8-8cc6-87fdbf26697e.png)

Aha! Link: https://kycc.aha.io/features/SL-62

**Comment by altninja** [comment]
@itsmeterrylin this is basically the currently expected programmed behaviour to update the dashboard to the new wallet after its unlocked
we don't have a final spec on exactly how this should be handled - should this be changed and not update the wallet dashboard or do something else?

overall let's better handle multiple wallets and profiles and quickly agree on something that we can implement

**Comment by altninja** [comment]
this is deprecated, dashboard doesn't change related to LWS activities
