### ISSUE TITLE
Client Library Releases

### ISSUE THREAD

**Issue by altninja** [SelfKeyFoundation/selfkey-login#9]
Develop 3 client libraries to released:
- `selfkey-web-client` JavaScript
- `selfkey-angular` AngularJS
- `selfkey-react` ReactJS

Be made available as packages on NPM and download from SelfKey GitHub

Aha! Link: https://kycc.aha.io/features/SL-66

**Comment by sk91** [comment]
@altninja so it will not be hosted but embedded?

I will be a huge pain to release new versions that way, since we cannot controll user code. It should be controlled by us

Since we need to coordinate lib releases with browser extension releases it will be even more of an issue

**Comment by altninja** [comment]
@sk91 lets chat more about this and figure out best solution

**Comment by altninja** [comment]
@rodrigopavezi need to follow this probably good idea to get your input on the implementation
